# Generated by Django 3.1.5 on 2021-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_bookmarks',
            name='clean_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime_bookmarks',
            name='anime_title',
            field=models.CharField(max_length=128),
        ),
    ]
