# Generated by Django 3.1.5 on 2021-02-24 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aniCategory', '0002_auto_20210211_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_bookmarks',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='24-February-2021'),
            preserve_default=False,
        ),
    ]
