# Generated by Django 3.1.5 on 2021-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniCategory', '0003_anime_bookmarks_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_bookmarks',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
